[2022-10-04T08:17:43.287+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v3.create_table manual__2022-10-04T08:17:42.084356+00:00 [queued]>
[2022-10-04T08:17:43.300+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v3.create_table manual__2022-10-04T08:17:42.084356+00:00 [queued]>
[2022-10-04T08:17:43.300+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:17:43.300+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-10-04T08:17:43.300+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:17:43.320+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-10-04 08:17:42.084356+00:00
[2022-10-04T08:17:43.325+0000] {standard_task_runner.py:54} INFO - Started process 12852 to run task
[2022-10-04T08:17:43.328+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v3', 'create_table', 'manual__2022-10-04T08:17:42.084356+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpbxereiio']
[2022-10-04T08:17:43.329+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask create_table
[2022-10-04T08:17:43.330+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_operator.py
[2022-10-04T08:17:43.500+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_v3.create_table manual__2022-10-04T08:17:42.084356+00:00 [running]> on host e877189be071
[2022-10-04T08:17:43.787+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v3
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T08:17:42.084356+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T08:17:42.084356+00:00
[2022-10-04T08:17:43.798+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T08:17:43.818+0000] {sql.py:315} INFO - Running statement: 
            create table if not exists dag_runs(
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        , parameters: None
[2022-10-04T08:17:43.830+0000] {postgres.py:96} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-10-04T08:17:43.845+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_v3, task_id=create_table, execution_date=20221004T081742, start_date=20221004T081743, end_date=20221004T081743
[2022-10-04T08:17:43.903+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-04T08:17:43.941+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
