[2022-10-04T08:18:04.239+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v3.insert_data manual__2022-10-04T08:17:59.345409+00:00 [queued]>
[2022-10-04T08:18:04.263+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v3.insert_data manual__2022-10-04T08:17:59.345409+00:00 [queued]>
[2022-10-04T08:18:04.264+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:18:04.264+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-10-04T08:18:04.264+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:18:04.300+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_data> on 2022-10-04 08:17:59.345409+00:00
[2022-10-04T08:18:04.308+0000] {standard_task_runner.py:54} INFO - Started process 12901 to run task
[2022-10-04T08:18:04.314+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v3', 'insert_data', 'manual__2022-10-04T08:17:59.345409+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpw7l2s_5f']
[2022-10-04T08:18:04.317+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask insert_data
[2022-10-04T08:18:04.319+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_operator.py
[2022-10-04T08:18:04.706+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_v3.insert_data manual__2022-10-04T08:17:59.345409+00:00 [running]> on host e877189be071
[2022-10-04T08:18:05.101+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v3
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T08:17:59.345409+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T08:17:59.345409+00:00
[2022-10-04T08:18:05.123+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T08:18:05.150+0000] {sql.py:315} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-10-04', 'dag_with_postgres_v3')
        , parameters: None
[2022-10-04T08:18:05.160+0000] {sql.py:324} INFO - Rows affected: 1
[2022-10-04T08:18:05.194+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_v3, task_id=insert_data, execution_date=20221004T081759, start_date=20221004T081804, end_date=20221004T081805
[2022-10-04T08:18:05.261+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-04T08:18:05.310+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
