[2022-10-04T08:11:12.867+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v2.insert_data manual__2022-10-04T08:11:08.252477+00:00 [queued]>
[2022-10-04T08:11:12.893+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v2.insert_data manual__2022-10-04T08:11:08.252477+00:00 [queued]>
[2022-10-04T08:11:12.894+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:11:12.894+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-10-04T08:11:12.894+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:11:12.933+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_data> on 2022-10-04 08:11:08.252477+00:00
[2022-10-04T08:11:12.940+0000] {standard_task_runner.py:54} INFO - Started process 12146 to run task
[2022-10-04T08:11:12.946+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v2', 'insert_data', 'manual__2022-10-04T08:11:08.252477+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp0kpcpzch']
[2022-10-04T08:11:12.949+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask insert_data
[2022-10-04T08:11:12.951+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_operator.py
[2022-10-04T08:11:13.260+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_v2.insert_data manual__2022-10-04T08:11:08.252477+00:00 [running]> on host e877189be071
[2022-10-04T08:11:13.692+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v2
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T08:11:08.252477+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T08:11:08.252477+00:00
[2022-10-04T08:11:13.710+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T08:11:13.736+0000] {sql.py:315} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-10-04', 'dag_with_postgres_v2')
        , parameters: None
[2022-10-04T08:11:13.745+0000] {sql.py:324} INFO - Rows affected: 1
[2022-10-04T08:11:13.776+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_v2, task_id=insert_data, execution_date=20221004T081108, start_date=20221004T081112, end_date=20221004T081113
[2022-10-04T08:11:13.843+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-04T08:11:13.894+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
