[2022-10-04T11:45:32.785+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_minio_s3_v1.sensor_minio_s3 scheduled__2022-10-02T00:00:00+00:00 [queued]>
[2022-10-04T11:45:32.811+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_minio_s3_v1.sensor_minio_s3 scheduled__2022-10-02T00:00:00+00:00 [queued]>
[2022-10-04T11:45:32.812+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T11:45:32.812+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 3
[2022-10-04T11:45:32.813+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T11:45:32.855+0000] {taskinstance.py:1383} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2022-10-02 00:00:00+00:00
[2022-10-04T11:45:32.863+0000] {standard_task_runner.py:54} INFO - Started process 10470 to run task
[2022-10-04T11:45:32.872+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v1', 'sensor_minio_s3', 'scheduled__2022-10-02T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio_s3.py', '--cfg-path', '/tmp/tmpv895gftb']
[2022-10-04T11:45:32.876+0000] {standard_task_runner.py:83} INFO - Job 98: Subtask sensor_minio_s3
[2022-10-04T11:45:32.879+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_minio_s3.py
[2022-10-04T11:45:33.288+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 98 for task sensor_minio_s3 (Dag 'dag_with_minio_s3_v1' could not be found; either it does not exist or it failed to parse.; 10470)
[2022-10-04T11:45:33.325+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-10-04T11:45:33.346+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
