[2022-10-04T08:18:15.625+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v3.insert_data scheduled__2022-10-02T00:00:00+00:00 [queued]>
[2022-10-04T08:18:15.653+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v3.insert_data scheduled__2022-10-02T00:00:00+00:00 [queued]>
[2022-10-04T08:18:15.653+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:18:15.653+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-10-04T08:18:15.654+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-10-04T08:18:15.692+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_data> on 2022-10-02 00:00:00+00:00
[2022-10-04T08:18:15.700+0000] {standard_task_runner.py:54} INFO - Started process 12935 to run task
[2022-10-04T08:18:15.715+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_v3', 'insert_data', 'scheduled__2022-10-02T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmprer2hraq']
[2022-10-04T08:18:15.728+0000] {standard_task_runner.py:83} INFO - Job 59: Subtask insert_data
[2022-10-04T08:18:15.731+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/dag_with_postgres_operator.py
[2022-10-04T08:18:16.056+0000] {task_command.py:384} INFO - Running <TaskInstance: dag_with_postgres_v3.insert_data scheduled__2022-10-02T00:00:00+00:00 [running]> on host e877189be071
[2022-10-04T08:18:16.556+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v3
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-10-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-02T00:00:00+00:00
[2022-10-04T08:18:16.597+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-10-04T08:18:16.646+0000] {sql.py:315} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2022-10-02', 'dag_with_postgres_v3')
        , parameters: None
[2022-10-04T08:18:16.658+0000] {sql.py:324} INFO - Rows affected: 1
[2022-10-04T08:18:16.704+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_v3, task_id=insert_data, execution_date=20221002T000000, start_date=20221004T081815, end_date=20221004T081816
[2022-10-04T08:18:16.770+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-10-04T08:18:16.826+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
